// frontend/components/businesses/BusinessDetail.vue
<script setup lang="ts">
import {
  ArrowLeft,
  Star,
  ShieldOff,
  Shield,
  Trash2,
} from "lucide-vue-next";
import type { BusinessDetail } from "~/types";

const props = defineProps<{
  business: BusinessDetail;
}>();

const emit = defineEmits<{
  refresh: [];
}>();

const pipeline = usePipeline();
const { blacklistAdd, blacklistRemove, deleteBusiness } = useBusinessActions();
const toast = useToast();

const deleteConfirmRef = ref<{ open: () => void; close: () => void } | null>(null);

const RUNNING_STATUSES = new Set([
  "running_enrich",
  "running_generate",
  "running_test",
  "running_deploy",
  "running_email",
]);

const NO_ACTION_STATUSES = new Set([
  "emailed",
  "email_queued",
  "opted_out",
]);

const STATUS_TO_NEXT: Record<string, { label: string; step: string }> = {
  searched: { label: "Enrich", step: "enrich" },
  enriched: { label: "Generate", step: "generate" },
  generated: { label: "Test", step: "test" },
  tested: { label: "Deploy", step: "deploy" },
  deployed: { label: "Email", step: "email" },
  error_enrich: { label: "Retry Enrich", step: "enrich" },
  error_generate: { label: "Retry Generate", step: "generate" },
  error_test: { label: "Retry Test", step: "test" },
  error_deploy: { label: "Retry Deploy", step: "deploy" },
  error_email: { label: "Retry Email", step: "email" },
  error_run: { label: "Retry Enrich", step: "enrich" },
};

const STEP_TO_TRIGGER: Record<string, (ids: string[]) => Promise<unknown>> = {
  enrich: (ids) => pipeline.triggerEnrich(ids),
  generate: (ids) => pipeline.triggerGenerate(ids),
  test: (ids) => pipeline.triggerTest(ids),
  deploy: (ids) => pipeline.triggerDeploy(ids),
  email: (ids) => pipeline.triggerEmail(ids),
};

const isRunning = computed(() => RUNNING_STATUSES.has(props.business.status));
const noAction = computed(() => NO_ACTION_STATUSES.has(props.business.status));
const nextAction = computed(() => STATUS_TO_NEXT[props.business.status]);
const isOptedOut = computed(() => props.business.status === "opted_out");

const actionPending = ref(false);
const blacklistPending = ref(false);

async function handleNextAction() {
  if (!nextAction.value) return;
  const trigger = STEP_TO_TRIGGER[nextAction.value.step];
  if (!trigger) return;

  actionPending.value = true;
  try {
    await trigger([props.business.place_id]);
    toast.push(`${nextAction.value.label} started`, "success");
    emit("refresh");
  } catch (e) {
    toast.push(e instanceof Error ? e.message : "Action failed", "error");
  } finally {
    actionPending.value = false;
  }
}

async function handleBlacklistToggle() {
  blacklistPending.value = true;
  try {
    if (isOptedOut.value) {
      await blacklistRemove(props.business.place_id);
      toast.push("Removed from blacklist", "success");
    } else {
      await blacklistAdd(props.business.place_id);
      toast.push("Added to blacklist", "success");
    }
    emit("refresh");
  } catch (e) {
    toast.push(e instanceof Error ? e.message : "Action failed", "error");
  } finally {
    blacklistPending.value = false;
  }
}

async function handleDelete() {
  try {
    await deleteBusiness(props.business.place_id);
    toast.push("Business deleted", "success");
    navigateTo("/businesses");
  } catch (e) {
    toast.push(e instanceof Error ? e.message : "Delete failed", "error");
  }
}
</script>

<template>
  <div class="space-y-6">
    <!-- Header -->
    <div>
      <NuxtLink to="/businesses" class="link link-primary text-sm flex items-center gap-1 mb-2">
        <ArrowLeft class="h-4 w-4" />
        Businesses
      </NuxtLink>

      <div class="flex flex-wrap items-center gap-3">
        <h1 class="text-2xl font-semibold">{{ business.name }}</h1>
        <SharedStatusBadge :status="business.status" />
        <span v-if="business.primary_type" class="text-base-content/60 text-sm">
          {{ business.primary_type.replace(/_/g, " ") }}
        </span>
        <span v-if="business.rating > 0" class="flex items-center gap-1 text-sm">
          <Star class="h-4 w-4 text-warning" />
          {{ business.rating.toFixed(1) }}
          <span class="text-base-content/60">({{ business.reviews }})</span>
        </span>
      </div>
    </div>

    <!-- Pipeline Graph -->
    <SharedPipelineGraph :status="business.status" />

    <!-- Action Buttons -->
    <div class="flex flex-wrap items-center gap-2">
      <!-- Next step button -->
      <button
        v-if="nextAction && !isRunning && !noAction"
        class="btn btn-primary btn-sm"
        :disabled="actionPending"
        @click="handleNextAction"
      >
        <span v-if="actionPending" class="loading loading-spinner loading-xs" />
        {{ nextAction.label }}
      </button>

      <button
        v-if="isRunning"
        class="btn btn-sm btn-disabled"
        disabled
      >
        <span class="loading loading-spinner loading-xs" />
        Running...
      </button>

      <div class="flex-1" />

      <!-- Blacklist toggle -->
      <button
        class="btn btn-outline btn-sm"
        :class="isOptedOut ? 'btn-success' : 'btn-warning'"
        :disabled="blacklistPending"
        @click="handleBlacklistToggle"
      >
        <Shield v-if="isOptedOut" class="h-4 w-4" />
        <ShieldOff v-else class="h-4 w-4" />
        {{ isOptedOut ? "Unblacklist" : "Blacklist" }}
      </button>

      <!-- Delete -->
      <button
        class="btn btn-error btn-outline btn-sm"
        @click="deleteConfirmRef?.open()"
      >
        <Trash2 class="h-4 w-4" />
        Delete
      </button>
    </div>

    <!-- Info Cards -->
    <BusinessesInfoCards :business="business" @refresh="$emit('refresh')" />

    <SharedConfirmDialog
      ref="deleteConfirmRef"
      title="Delete business?"
      :description="`Permanently delete ${business.name}? This cannot be undone.`"
      confirm-label="Delete"
      confirm-class="btn-error"
      @confirm="handleDelete"
    />
  </div>
</template>

// frontend/src/components/businesses/BusinessDetail.tsx
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import {
  Trash2,
  ShieldBan,
  ShieldCheck,
  ArrowLeft,
  Loader2,
  Star,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import StatusBadge from "./StatusBadge";
import PipelineGraph from "./PipelineGraph";
import InfoCards from "./InfoCards";
import {
  useBlacklistAddBusinessesPlaceIdBlacklistPost,
  useBlacklistRemoveBusinessesPlaceIdBlacklistDelete,
  useDeleteBusinessBusinessesPlaceIdDelete,
} from "@/api/endpoints/businesses/businesses";
import {
  usePipelineEnrichPipelineEnrichPost,
  usePipelineGeneratePipelineGeneratePost,
  usePipelineTestPipelineTestPost,
  usePipelineDeployPipelineDeployPost,
  usePipelineEmailPipelineEmailPost,
} from "@/api/endpoints/pipeline/pipeline";

const STATUS_TO_NEXT: Record<
  string,
  { label: string; step: string } | undefined
> = {
  searched: { label: "Enrich", step: "enrich" },
  enriched: { label: "Generate", step: "generate" },
  generated: { label: "Test", step: "test" },
  tested: { label: "Deploy", step: "deploy" },
  deployed: { label: "Email", step: "email" },
  error_enrich: { label: "Retry Enrich", step: "enrich" },
  error_generate: { label: "Retry Generate", step: "generate" },
  error_test: { label: "Retry Test", step: "test" },
  error_deploy: { label: "Retry Deploy", step: "deploy" },
  error_email: { label: "Retry Email", step: "email" },
};

const NO_ACTION_STATUSES = new Set([
  "emailed",
  "email_queued",
  "opted_out",
]);

const RUNNING_STATUSES = new Set([
  "running_enrich",
  "running_generate",
  "running_test",
  "running_deploy",
  "running_email",
]);

export interface BusinessData {
  place_id: string;
  name?: string;
  address?: string;
  phone?: string;
  rating?: number;
  reviews?: number;
  lead_score?: number;
  status?: string;
  primary_type?: string;
  vercel_url?: string;
  error_detail?: string;
  [key: string]: unknown;
}

interface BusinessDetailProps {
  business: BusinessData;
  onRefresh: () => void;
}

export default function BusinessDetail({
  business,
  onRefresh,
}: BusinessDetailProps) {
  const navigate = useNavigate();
  const status = business.status ?? "searched";
  const isOptedOut = status === "opted_out";
  const isRunning = RUNNING_STATUSES.has(status);
  const nextAction = STATUS_TO_NEXT[status];
  const showAction = !NO_ACTION_STATUSES.has(status) && !isRunning;

  const blacklistAdd = useBlacklistAddBusinessesPlaceIdBlacklistPost();
  const blacklistRemove =
    useBlacklistRemoveBusinessesPlaceIdBlacklistDelete();
  const deleteBusiness = useDeleteBusinessBusinessesPlaceIdDelete();

  const enrichMutation = usePipelineEnrichPipelineEnrichPost();
  const generateMutation = usePipelineGeneratePipelineGeneratePost();
  const testMutation = usePipelineTestPipelineTestPost();
  const deployMutation = usePipelineDeployPipelineDeployPost();
  const emailMutation = usePipelineEmailPipelineEmailPost();

  const handleBlacklistToggle = () => {
    if (isOptedOut) {
      blacklistRemove.mutate(
        { placeId: business.place_id },
        {
          onSuccess: () => {
            toast.success("Removed from blacklist");
            onRefresh();
          },
          onError: () => toast.error("Failed to remove from blacklist"),
        },
      );
    } else {
      blacklistAdd.mutate(
        { placeId: business.place_id },
        {
          onSuccess: () => {
            toast.success("Added to blacklist");
            onRefresh();
          },
          onError: () => toast.error("Failed to add to blacklist"),
        },
      );
    }
  };

  const handleDelete = () => {
    deleteBusiness.mutate(
      { placeId: business.place_id },
      {
        onSuccess: () => {
          toast.success("Business deleted");
          navigate("/businesses");
        },
        onError: () => toast.error("Failed to delete business"),
      },
    );
  };

  const handleNextStep = () => {
    if (!nextAction) return;
    const data = { data: { place_ids: [business.place_id] } };
    const opts = {
      onSuccess: () => {
        toast.success(`${nextAction.label} started`);
        onRefresh();
      },
      onError: () => toast.error(`${nextAction.label} failed`),
    };

    switch (nextAction.step) {
      case "enrich":
        enrichMutation.mutate(data, opts);
        break;
      case "generate":
        generateMutation.mutate(data, opts);
        break;
      case "test":
        testMutation.mutate(data, opts);
        break;
      case "deploy":
        deployMutation.mutate(data, opts);
        break;
      case "email":
        emailMutation.mutate(data, opts);
        break;
    }
  };

  const anyPending =
    enrichMutation.isPending ||
    generateMutation.isPending ||
    testMutation.isPending ||
    deployMutation.isPending ||
    emailMutation.isPending;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <button
          type="button"
          className="mb-2 flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"
          onClick={() => navigate("/businesses")}
        >
          <ArrowLeft className="h-4 w-4" />
          Businesses
        </button>
        <div className="flex flex-wrap items-center gap-3">
          <h1 className="text-2xl font-semibold">
            {business.name ?? "Unknown Business"}
          </h1>
          <StatusBadge status={status} />
          {business.primary_type && (
            <span className="text-sm capitalize text-muted-foreground">
              {(business.primary_type as string).replace(/_/g, " ")}
            </span>
          )}
          {business.rating != null && (
            <span className="flex items-center gap-1 text-sm">
              <Star className="h-3.5 w-3.5 fill-amber-400 text-amber-400" />
              {business.rating}
              {business.reviews != null && (
                <span className="text-muted-foreground">
                  ({business.reviews})
                </span>
              )}
            </span>
          )}
        </div>
      </div>

      {/* Pipeline graph */}
      <PipelineGraph status={status} />

      {/* Actions */}
      <div className="flex flex-wrap items-center gap-2">
        {isRunning && (
          <Button disabled>
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            Running...
          </Button>
        )}
        {showAction && nextAction && (
          <Button onClick={handleNextStep} disabled={anyPending}>
            {anyPending && (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            )}
            {nextAction.label}
          </Button>
        )}
        <Button
          variant={isOptedOut ? "default" : "outline"}
          size="sm"
          onClick={handleBlacklistToggle}
        >
          {isOptedOut ? (
            <>
              <ShieldCheck className="mr-1 h-4 w-4" /> Unblacklist
            </>
          ) : (
            <>
              <ShieldBan className="mr-1 h-4 w-4" /> Blacklist
            </>
          )}
        </Button>
        <AlertDialog>
          <AlertDialogTrigger asChild>
            <Button variant="destructive" size="sm">
              <Trash2 className="mr-1 h-4 w-4" /> Delete
            </Button>
          </AlertDialogTrigger>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Delete business?</AlertDialogTitle>
              <AlertDialogDescription>
                This will permanently remove{" "}
                {business.name ?? "this business"} from the database.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancel</AlertDialogCancel>
              <AlertDialogAction onClick={handleDelete}>
                Delete
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      </div>

      {/* Info cards */}
      <InfoCards business={business} onRefresh={onRefresh} />
    </div>
  );
}
