// frontend/components/shared/StatusBadge.vue
<script setup lang="ts">
const props = defineProps<{
  status: string;
}>();

const badgeClass = computed(() => {
  const s = props.status;

  if (s.startsWith("running_")) return "badge badge-info animate-pulse";
  if (s.startsWith("error_")) return "badge badge-error";

  const map: Record<string, string> = {
    searched: "badge badge-info",
    enriched: "badge bg-purple-600 text-white border-purple-600",
    generated: "badge badge-success",
    tested: "badge bg-teal-600 text-white border-teal-600",
    deployed: "badge badge-success badge-outline",
    email_queued: "badge badge-warning",
    emailed: "badge badge-accent",
    opted_out: "badge badge-ghost",
  };

  return map[s] ?? "badge";
});

const label = computed(() =>
  props.status.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
);
</script>

<template>
  <span :class="badgeClass" class="badge-sm">{{ label }}</span>
</template>

// frontend/src/components/businesses/StatusBadge.tsx
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

const STATUS_COLORS: Record<string, string> = {
  searched: "bg-blue-100 text-blue-800",
  enriched: "bg-purple-100 text-purple-800",
  generated: "bg-green-100 text-green-800",
  tested: "bg-teal-100 text-teal-800",
  deployed: "bg-emerald-100 text-emerald-800",
  email_queued: "bg-amber-100 text-amber-800",
  emailed: "bg-indigo-100 text-indigo-800",
  running_enrich: "bg-blue-100 text-blue-800 animate-pulse",
  running_generate: "bg-blue-100 text-blue-800 animate-pulse",
  running_test: "bg-blue-100 text-blue-800 animate-pulse",
  running_deploy: "bg-blue-100 text-blue-800 animate-pulse",
  running_email: "bg-blue-100 text-blue-800 animate-pulse",
  error_enrich: "bg-red-100 text-red-800",
  error_generate: "bg-red-100 text-red-800",
  error_test: "bg-red-100 text-red-800",
  error_deploy: "bg-red-100 text-red-800",
  error_email: "bg-red-100 text-red-800",
  error_run: "bg-red-100 text-red-800",
  opted_out: "bg-gray-100 text-gray-800",
};

interface StatusBadgeProps {
  status: string;
}

export default function StatusBadge({ status }: StatusBadgeProps) {
  return (
    <Badge
      variant="secondary"
      className={cn(STATUS_COLORS[status] ?? "")}
    >
      {status.replace(/_/g, " ")}
    </Badge>
  );
}
