// frontend/src/components/businesses/InfoCards.tsx
import { useState } from "react";
import {
  MapPin,
  Phone,
  Mail,
  ExternalLink,
  Star,
  ChevronDown,
  Clock,
  CreditCard,
} from "lucide-react";
import { toast } from "sonner";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import { useUpdateStatusBusinessesPlaceIdStatusPatch } from "@/api/endpoints/businesses/businesses";
import type { BusinessData } from "./BusinessDetail";

const RESET_STATUSES = [
  "searched",
  "enriched",
  "generated",
  "tested",
  "deployed",
  "email_queued",
  "emailed",
];

interface InfoCardsProps {
  business: BusinessData;
  onRefresh: () => void;
}

export default function InfoCards({ business, onRefresh }: InfoCardsProps) {
  return (
    <div className="grid gap-4 md:grid-cols-2">
      <ContactCard business={business} />
      <ScoresCard business={business} />
      <BusinessInfoCard business={business} />
      <ReviewsCard business={business} />
      <SiteDeploymentCard business={business} />
      <TestingCard business={business} />
      <ErrorCard business={business} onRefresh={onRefresh} />
      <MetadataCard business={business} />
    </div>
  );
}

function ContactCard({ business }: { business: BusinessData }) {
  const { address, phone, email, maps_url } = business as Record<
    string,
    unknown
  >;
  if (!address && !phone && !email && !maps_url) return null;

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-sm">Contact</CardTitle>
      </CardHeader>
      <CardContent className="space-y-2 text-sm">
        {address && (
          <div className="flex items-start gap-2">
            <MapPin className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" />
            <span>{address as string}</span>
          </div>
        )}
        {phone && (
          <div className="flex items-center gap-2">
            <Phone className="h-4 w-4 shrink-0 text-muted-foreground" />
            <a
              href={`tel:${phone as string}`}
              className="hover:underline"
            >
              {phone as string}
            </a>
          </div>
        )}
        {email && (email as string) !== "" && (
          <div className="flex items-center gap-2">
            <Mail className="h-4 w-4 shrink-0 text-muted-foreground" />
            <a
              href={`mailto:${email as string}`}
              className="hover:underline"
            >
              {email as string}
            </a>
          </div>
        )}
        {maps_url && (maps_url as string) !== "" && (
          <div className="flex items-center gap-2">
            <ExternalLink className="h-4 w-4 shrink-0 text-muted-foreground" />
            <a
              href={maps_url as string}
              target="_blank"
              rel="noopener noreferrer"
              className="hover:underline"
            >
              View on Google Maps
            </a>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function ScoresCard({ business }: { business: BusinessData }) {
  const leadScore = business.lead_score;
  const rating = business.rating;
  const reviews = business.reviews;
  const priceLevel = business.price_level as string | undefined;

  if (leadScore == null && rating == null) return null;

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-sm">Scores</CardTitle>
      </CardHeader>
      <CardContent className="space-y-3">
        {leadScore != null && (
          <div className="space-y-1">
            <div className="flex items-center justify-between text-sm">
              <span className="text-muted-foreground">Lead Score</span>
              <span className="font-semibold">{leadScore}/100</span>
            </div>
            <Progress value={leadScore} className="h-2" />
          </div>
        )}
        {rating != null && (
          <div className="flex items-center justify-between text-sm">
            <span className="text-muted-foreground">Rating</span>
            <span className="flex items-center gap-1 font-semibold">
              <Star className="h-3.5 w-3.5 fill-amber-400 text-amber-400" />
              {rating}
              {reviews != null && (
                <span className="font-normal text-muted-foreground">
                  ({reviews} reviews)
                </span>
              )}
            </span>
          </div>
        )}
        {priceLevel && (
          <div className="flex items-center justify-between text-sm">
            <span className="text-muted-foreground">Price Level</span>
            <span className="font-semibold">{priceLevel}</span>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function BusinessInfoCard({ business }: { business: BusinessData }) {
  const types = business.types as string[] | undefined;
  const businessStatus = business.business_status as string | undefined;
  const openingHours = business.opening_hours_summary as string | undefined;
  const acceptsCreditCards = business.accepts_credit_cards as
    | boolean
    | undefined;
  const editorialSummary = business.editorial_summary as string | undefined;

  if (
    !types?.length &&
    !businessStatus &&
    !openingHours &&
    acceptsCreditCards == null &&
    !editorialSummary
  )
    return null;

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-sm">Business Info</CardTitle>
      </CardHeader>
      <CardContent className="space-y-3 text-sm">
        {types && types.length > 0 && (
          <div className="flex flex-wrap gap-1">
            {types.map((t) => (
              <Badge key={t} variant="secondary" className="text-xs capitalize">
                {t.replace(/_/g, " ")}
              </Badge>
            ))}
          </div>
        )}
        {businessStatus && (
          <div className="flex items-center justify-between">
            <span className="text-muted-foreground">Status</span>
            <span>{businessStatus}</span>
          </div>
        )}
        {openingHours && (
          <div className="flex items-start gap-2">
            <Clock className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" />
            <span className="whitespace-pre-line">{openingHours}</span>
          </div>
        )}
        {acceptsCreditCards != null && (
          <div className="flex items-center gap-2">
            <CreditCard className="h-4 w-4 shrink-0 text-muted-foreground" />
            <span>
              {acceptsCreditCards
                ? "Accepts credit cards"
                : "No credit cards"}
            </span>
          </div>
        )}
        {editorialSummary && (
          <p className="text-muted-foreground italic">{editorialSummary}</p>
        )}
      </CardContent>
    </Card>
  );
}

function ReviewsCard({ business }: { business: BusinessData }) {
  const reviewTexts = business.review_texts as string[] | undefined;
  if (!reviewTexts?.length) return null;

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-sm">Reviews</CardTitle>
      </CardHeader>
      <CardContent className="space-y-2">
        {reviewTexts.map((text, i) => (
          <blockquote
            key={i}
            className="border-l-2 border-muted pl-3 text-sm italic text-muted-foreground"
          >
            {text}
          </blockquote>
        ))}
      </CardContent>
    </Card>
  );
}

function SiteDeploymentCard({ business }: { business: BusinessData }) {
  const vercelUrl = business.vercel_url as string | undefined;
  const emailSentAt = business.email_sent_at as string | undefined;
  if (!vercelUrl) return null;

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-sm">Site & Deployment</CardTitle>
      </CardHeader>
      <CardContent className="space-y-2 text-sm">
        <div className="flex items-center gap-2">
          <ExternalLink className="h-4 w-4 shrink-0 text-muted-foreground" />
          <a
            href={vercelUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="hover:underline"
          >
            {vercelUrl}
          </a>
        </div>
        {emailSentAt && emailSentAt !== "" && (
          <div className="text-muted-foreground">
            Email sent: {new Date(emailSentAt).toLocaleString("it-IT")}
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function TestingCard({ business }: { business: BusinessData }) {
  const iterations = business.test_iterations as number | undefined;
  const issues = business.test_issues as
    | Record<string, unknown>[]
    | undefined;

  if (!iterations || iterations === 0) return null;

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-sm">Testing</CardTitle>
      </CardHeader>
      <CardContent className="space-y-2 text-sm">
        <div className="flex items-center justify-between">
          <span className="text-muted-foreground">Iterations</span>
          <span className="font-semibold">{iterations}</span>
        </div>
        {issues && issues.length > 0 && (
          <Collapsible>
            <CollapsibleTrigger asChild>
              <Button variant="ghost" size="sm" className="gap-1 px-0 text-xs">
                {issues.length} issue{issues.length > 1 ? "s" : ""}
                <ChevronDown className="h-3 w-3" />
              </Button>
            </CollapsibleTrigger>
            <CollapsibleContent className="space-y-1 pt-1">
              {issues.map((issue, i) => (
                <div
                  key={i}
                  className="rounded bg-muted p-2 text-xs"
                >
                  {JSON.stringify(issue)}
                </div>
              ))}
            </CollapsibleContent>
          </Collapsible>
        )}
      </CardContent>
    </Card>
  );
}

function ErrorCard({
  business,
  onRefresh,
}: {
  business: BusinessData;
  onRefresh: () => void;
}) {
  const errorDetail = business.error_detail as string | undefined;
  const status = business.status ?? "";
  const [resetTo, setResetTo] = useState("");
  const updateStatus = useUpdateStatusBusinessesPlaceIdStatusPatch();

  if (!errorDetail || errorDetail === "") return null;

  const handleReset = () => {
    if (!resetTo) return;
    updateStatus.mutate(
      { placeId: business.place_id, data: { to: resetTo } },
      {
        onSuccess: () => {
          toast.success(`Status reset to ${resetTo}`);
          onRefresh();
        },
        onError: () => toast.error("Failed to reset status"),
      },
    );
  };

  return (
    <Card className="border-red-200 dark:border-red-900">
      <CardHeader className="pb-2">
        <CardTitle className="text-sm text-red-600 dark:text-red-400">
          Error
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-3 text-sm">
        <div>
          <span className="text-muted-foreground">Failed at: </span>
          <span className="font-medium">{status.replace(/_/g, " ")}</span>
        </div>
        <p className="text-muted-foreground">{errorDetail}</p>
        <div className="flex items-center gap-2">
          <Select value={resetTo} onValueChange={setResetTo}>
            <SelectTrigger className="w-40 h-8 text-xs">
              <SelectValue placeholder="Reset to..." />
            </SelectTrigger>
            <SelectContent>
              {RESET_STATUSES.map((s) => (
                <SelectItem key={s} value={s}>
                  {s.replace(/_/g, " ")}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Button
            size="sm"
            onClick={handleReset}
            disabled={!resetTo || updateStatus.isPending}
          >
            Reset
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

function MetadataCard({ business }: { business: BusinessData }) {
  const createdAt = business.created_at as string | undefined;
  const updatedAt = business.updated_at as string | undefined;

  if (!createdAt && !updatedAt) return null;

  const fmt = (d: string) => {
    try {
      return new Date(d).toLocaleString("it-IT");
    } catch {
      return d;
    }
  };

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-sm">Metadata</CardTitle>
      </CardHeader>
      <CardContent className="space-y-1 text-sm">
        {createdAt && (
          <div className="flex items-center justify-between">
            <span className="text-muted-foreground">Created</span>
            <span>{fmt(createdAt)}</span>
          </div>
        )}
        {updatedAt && (
          <div className="flex items-center justify-between">
            <span className="text-muted-foreground">Updated</span>
            <span>{fmt(updatedAt)}</span>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// frontend/components/businesses/InfoCards.vue
<script setup lang="ts">
import {
  MapPin,
  Phone,
  Mail,
  ExternalLink,
  Star,
  Clock,
  CreditCard,
  AlertTriangle,
  Calendar,
} from "lucide-vue-next";
import type { BusinessDetail } from "~/types";
import { formatDate } from "~/utils/formatters";

const props = defineProps<{
  business: BusinessDetail;
}>();

const emit = defineEmits<{
  refresh: [];
}>();

const { patchStatus } = useBusinessActions();
const toast = useToast();

const RESET_STATUSES = [
  "searched",
  "enriched",
  "generated",
  "tested",
  "deployed",
] as const;

const resetTo = ref("");
const resetPending = ref(false);

async function handleReset() {
  if (!resetTo.value) return;
  resetPending.value = true;
  try {
    await patchStatus(props.business.place_id, resetTo.value);
    toast.push(`Status reset to ${resetTo.value}`, "success");
    emit("refresh");
  } catch (e) {
    toast.push(e instanceof Error ? e.message : "Reset failed", "error");
  } finally {
    resetPending.value = false;
    resetTo.value = "";
  }
}

const hasContact = computed(
  () => props.business.address || props.business.phone || props.business.email || props.business.maps_url,
);

const hasScores = computed(
  () => props.business.lead_score > 0 || props.business.rating > 0,
);

const hasBusinessInfo = computed(
  () =>
    props.business.types?.length ||
    props.business.opening_hours_summary ||
    props.business.editorial_summary,
);

const hasReviews = computed(
  () => props.business.review_texts && props.business.review_texts.length > 0,
);

const hasSiteDeployment = computed(() => !!props.business.vercel_url);

const hasTesting = computed(() => props.business.test_iterations > 0);

const hasError = computed(() => !!props.business.error_detail);
</script>

<template>
  <div class="grid grid-cols-1 gap-4 md:grid-cols-2">
    <!-- Contact Card -->
    <div v-if="hasContact" class="card bg-base-200 card-compact">
      <div class="card-body">
        <h3 class="card-title text-sm">Contact</h3>
        <div class="space-y-2 text-sm">
          <div v-if="business.address" class="flex items-start gap-2">
            <MapPin class="h-4 w-4 shrink-0 text-base-content/60" />
            <span>{{ business.address }}</span>
          </div>
          <div v-if="business.phone" class="flex items-center gap-2">
            <Phone class="h-4 w-4 shrink-0 text-base-content/60" />
            <a :href="`tel:${business.phone}`" class="link link-primary">
              {{ business.phone }}
            </a>
          </div>
          <div v-if="business.email" class="flex items-center gap-2">
            <Mail class="h-4 w-4 shrink-0 text-base-content/60" />
            <a :href="`mailto:${business.email}`" class="link link-primary">
              {{ business.email }}
            </a>
          </div>
          <div v-if="business.maps_url" class="flex items-center gap-2">
            <ExternalLink class="h-4 w-4 shrink-0 text-base-content/60" />
            <a
              :href="business.maps_url"
              target="_blank"
              rel="noopener"
              class="link link-primary"
            >
              View on Google Maps
            </a>
          </div>
        </div>
      </div>
    </div>

    <!-- Scores Card -->
    <div v-if="hasScores" class="card bg-base-200 card-compact">
      <div class="card-body">
        <h3 class="card-title text-sm">Scores</h3>
        <div class="space-y-3">
          <div v-if="business.lead_score > 0">
            <div class="flex items-center justify-between text-sm">
              <span>Lead Score</span>
              <span class="font-semibold">{{ business.lead_score }}/100</span>
            </div>
            <progress
              class="progress progress-primary w-full"
              :value="business.lead_score"
              max="100"
            />
          </div>
          <div v-if="business.rating > 0" class="flex items-center gap-2 text-sm">
            <Star class="h-4 w-4 text-warning" />
            <span class="font-medium">{{ business.rating.toFixed(1) }}</span>
            <span class="text-base-content/60">({{ business.reviews }} reviews)</span>
          </div>
          <div v-if="business.price_level" class="text-sm text-base-content/60">
            Price: {{ business.price_level }}
          </div>
        </div>
      </div>
    </div>

    <!-- Business Info Card -->
    <div v-if="hasBusinessInfo" class="card bg-base-200 card-compact">
      <div class="card-body">
        <h3 class="card-title text-sm">Business Info</h3>
        <div class="space-y-2 text-sm">
          <div v-if="business.types?.length" class="flex flex-wrap gap-1">
            <span
              v-for="type in business.types"
              :key="type"
              class="badge badge-outline badge-xs"
            >
              {{ type.replace(/_/g, " ") }}
            </span>
          </div>
          <div v-if="business.business_status" class="text-base-content/60">
            Status: {{ business.business_status }}
          </div>
          <div v-if="business.opening_hours_summary" class="flex items-start gap-2">
            <Clock class="h-4 w-4 shrink-0 text-base-content/60" />
            <span>{{ business.opening_hours_summary }}</span>
          </div>
          <div v-if="business.accepts_credit_cards !== null" class="flex items-center gap-2">
            <CreditCard class="h-4 w-4 text-base-content/60" />
            <span>{{ business.accepts_credit_cards ? "Accepts cards" : "Cash only" }}</span>
          </div>
          <p v-if="business.editorial_summary" class="text-base-content/70 italic">
            {{ business.editorial_summary }}
          </p>
        </div>
      </div>
    </div>

    <!-- Reviews Card -->
    <div v-if="hasReviews" class="card bg-base-200 card-compact">
      <div class="card-body">
        <h3 class="card-title text-sm">Reviews</h3>
        <div class="space-y-2">
          <blockquote
            v-for="(review, i) in business.review_texts"
            :key="i"
            class="border-l-2 border-base-300 pl-3 text-sm text-base-content/70 italic"
          >
            "{{ review }}"
          </blockquote>
        </div>
      </div>
    </div>

    <!-- Site & Deployment Card -->
    <div v-if="hasSiteDeployment" class="card bg-base-200 card-compact">
      <div class="card-body">
        <h3 class="card-title text-sm">Site & Deployment</h3>
        <div class="space-y-2 text-sm">
          <div class="flex items-center gap-2">
            <ExternalLink class="h-4 w-4 text-base-content/60" />
            <a
              :href="business.vercel_url ?? undefined"
              target="_blank"
              rel="noopener"
              class="link link-primary"
            >
              {{ business.vercel_url }}
            </a>
          </div>
          <div v-if="business.email_sent_at" class="text-base-content/60">
            Email sent: {{ formatDate(business.email_sent_at) }}
          </div>
        </div>
      </div>
    </div>

    <!-- Testing Card -->
    <div v-if="hasTesting" class="card bg-base-200 card-compact">
      <div class="card-body">
        <h3 class="card-title text-sm">Testing</h3>
        <div class="text-sm">
          <p>Iterations: {{ business.test_iterations }}</p>
          <details v-if="business.test_issues?.length" class="mt-2">
            <summary class="cursor-pointer text-base-content/60">
              {{ business.test_issues.length }} issues
            </summary>
            <ul class="mt-1 space-y-1 pl-4">
              <li
                v-for="(issue, i) in business.test_issues"
                :key="i"
                class="text-xs text-base-content/60"
              >
                {{ typeof issue === "object" ? JSON.stringify(issue) : issue }}
              </li>
            </ul>
          </details>
        </div>
      </div>
    </div>

    <!-- Error Card -->
    <div v-if="hasError" class="card bg-error/10 border border-error card-compact">
      <div class="card-body">
        <h3 class="card-title text-sm text-error">
          <AlertTriangle class="h-4 w-4" />
          Error
        </h3>
        <div class="space-y-2 text-sm">
          <p class="text-error">{{ business.error_detail }}</p>
          <div class="flex items-center gap-2">
            <select
              v-model="resetTo"
              class="select select-bordered select-sm"
            >
              <option value="" disabled>Reset to...</option>
              <option v-for="s in RESET_STATUSES" :key="s" :value="s">
                {{ s }}
              </option>
            </select>
            <button
              class="btn btn-warning btn-sm"
              :disabled="!resetTo || resetPending"
              @click="handleReset"
            >
              <span v-if="resetPending" class="loading loading-spinner loading-xs" />
              Reset
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Metadata Card -->
    <div class="card bg-base-200 card-compact">
      <div class="card-body">
        <h3 class="card-title text-sm">
          <Calendar class="h-4 w-4" />
          Metadata
        </h3>
        <div class="space-y-1 text-sm text-base-content/60">
          <p>Created: {{ formatDate(business.created_at) }}</p>
          <p>Updated: {{ formatDate(business.updated_at) }}</p>
        </div>
      </div>
    </div>
  </div>
</template>
