// frontend/src/components/pipeline/SearchForm.tsx
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { usePipelineSearchPipelineSearchPost } from "@/api/endpoints/pipeline/pipeline";

const searchSchema = z.object({
  location: z.string().min(1, "Location is required"),
  query: z.string().min(1, "Query is required"),
  types: z.string().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(10),
  min_score: z.coerce.number().int().min(0).max(60).default(0),
  grid_size: z.coerce.number().int().min(1).max(10).default(3),
});

type SearchFormValues = z.infer<typeof searchSchema>;

interface SearchFormProps {
  onJobStarted: (jobId: string) => void;
}

export default function SearchForm({ onJobStarted }: SearchFormProps) {
  const {
    register,
    handleSubmit,
    setValue,
    watch,
    formState: { errors },
  } = useForm<SearchFormValues>({
    resolver: zodResolver(searchSchema),
    defaultValues: {
      location: "",
      query: "",
      types: "",
      limit: 10,
      min_score: 0,
      grid_size: 3,
    },
  });

  const mutation = usePipelineSearchPipelineSearchPost();
  const minScore = watch("min_score");

  const onSubmit = (data: SearchFormValues) => {
    const types = data.types
      ? data.types.split(",").map((t) => t.trim()).filter(Boolean)
      : [];

    mutation.mutate(
      {
        data: {
          location: data.location,
          query: data.query,
          types,
          limit: data.limit,
          min_score: data.min_score,
          grid_size: data.grid_size,
        },
      },
      {
        onSuccess: (response) => {
          const jobId = response.data.job_id;
          toast.success(`Search started (job: ${jobId.slice(0, 8)}...)`);
          onJobStarted(jobId);
        },
        onError: (error) => {
          toast.error(
            `Search failed: ${error instanceof Error ? error.message : "Unknown error"}`,
          );
        },
      },
    );
  };

  return (
    <form
      onSubmit={(e) => void handleSubmit(onSubmit)(e)}
      className="space-y-4"
    >
      <div className="grid gap-4 md:grid-cols-2">
        <div className="space-y-2">
          <Label htmlFor="location">Location *</Label>
          <Input
            id="location"
            placeholder="e.g. Milano, Italia"
            {...register("location")}
          />
          {errors.location && (
            <p className="text-xs text-destructive">{errors.location.message}</p>
          )}
        </div>
        <div className="space-y-2">
          <Label htmlFor="query">Query *</Label>
          <Input
            id="query"
            placeholder="e.g. ristorante"
            {...register("query")}
          />
          {errors.query && (
            <p className="text-xs text-destructive">{errors.query.message}</p>
          )}
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        <div className="space-y-2">
          <Label htmlFor="types">Types (comma-separated)</Label>
          <Input
            id="types"
            placeholder="e.g. restaurant, cafe"
            {...register("types")}
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="limit">Limit</Label>
          <Input
            id="limit"
            type="number"
            min={1}
            max={100}
            {...register("limit")}
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="grid_size">Grid Size</Label>
          <Input
            id="grid_size"
            type="number"
            min={1}
            max={10}
            {...register("grid_size")}
          />
        </div>
      </div>

      <div className="space-y-2">
        <Label>Min Score: {minScore}</Label>
        <Slider
          min={0}
          max={60}
          step={1}
          value={[minScore]}
          onValueChange={([val]) => setValue("min_score", val)}
        />
      </div>

      <Button type="submit" disabled={mutation.isPending}>
        {mutation.isPending ? "Starting search..." : "Start Search"}
      </Button>
    </form>
  );
}

// frontend/components/search/SearchForm.vue
<script setup lang="ts">
const emit = defineEmits<{
  "job-started": [jobId: string];
}>();

const { triggerSearch } = usePipeline();
const toast = useToast();

const location = ref("");
const query = ref("");
const types = ref<string[]>([]);
const showAdvanced = ref(false);
const limit = ref(10);
const minScore = ref(0);
const gridSize = ref(3);
const loading = ref(false);

async function handleSubmit() {
  if (!location.value.trim() || !query.value.trim()) return;

  loading.value = true;
  try {
    const result = await triggerSearch({
      location: location.value.trim(),
      query: query.value.trim(),
      types: types.value.length > 0 ? types.value : undefined,
      limit: limit.value,
      min_score: minScore.value,
      grid_size: gridSize.value,
    });
    emit("job-started", result.job_id);
    toast.push("Search started", "success");
  } catch (e) {
    toast.push(
      e instanceof Error ? e.message : "Search failed",
      "error",
    );
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <form @submit.prevent="handleSubmit" class="space-y-4">
    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
      <div class="form-control">
        <label class="label" for="search-location">
          <span class="label-text">Location *</span>
        </label>
        <input
          id="search-location"
          v-model="location"
          type="text"
          placeholder="e.g. Milano, Roma..."
          class="input input-bordered w-full"
          required
        />
      </div>

      <div class="form-control">
        <label class="label" for="search-query">
          <span class="label-text">Query *</span>
        </label>
        <input
          id="search-query"
          v-model="query"
          type="text"
          placeholder="e.g. ristorante, parrucchiere..."
          class="input input-bordered w-full"
          required
        />
      </div>
    </div>

    <SearchTypesMultiSelect v-model="types" />

    <!-- Advanced options -->
    <details @toggle="showAdvanced = ($event.target as HTMLDetailsElement).open">
      <summary class="cursor-pointer text-sm font-medium text-base-content/60 hover:text-base-content">
        Advanced Options
      </summary>
      <div class="mt-3 grid grid-cols-1 gap-4 sm:grid-cols-3">
        <div class="form-control">
          <label class="label" for="search-limit">
            <span class="label-text">Limit</span>
          </label>
          <input
            id="search-limit"
            v-model.number="limit"
            type="number"
            min="1"
            max="100"
            class="input input-bordered input-sm w-full"
          />
        </div>

        <div class="form-control">
          <label class="label" for="search-min-score">
            <span class="label-text">Min Score</span>
          </label>
          <input
            id="search-min-score"
            v-model.number="minScore"
            type="number"
            min="0"
            max="100"
            class="input input-bordered input-sm w-full"
          />
        </div>

        <div class="form-control">
          <label class="label" for="search-grid-size">
            <span class="label-text">Grid Size</span>
          </label>
          <input
            id="search-grid-size"
            v-model.number="gridSize"
            type="number"
            min="1"
            max="10"
            class="input input-bordered input-sm w-full"
          />
        </div>
      </div>
    </details>

    <button
      type="submit"
      class="btn btn-primary"
      :disabled="loading || !location.trim() || !query.trim()"
    >
      <span v-if="loading" class="loading loading-spinner loading-sm" />
      {{ loading ? "Searching..." : "Search" }}
    </button>
  </form>
</template>
