// frontend/components/search/SearchResultsTable.vue
<script setup lang="ts">
import { ArrowUpDown } from "lucide-vue-next";
import type { BusinessSummary, SortDir } from "~/types";

const props = defineProps<{
  results: BusinessSummary[];
}>();

const selected = defineModel<Set<string>>("selected", {
  default: () => new Set(),
});

const sortField = ref<"rating" | "reviews" | "lead_score" | null>(null);
const sortDir = ref<SortDir>("desc");

function toggleSort(field: "rating" | "reviews" | "lead_score") {
  if (sortField.value === field) {
    sortDir.value = sortDir.value === "asc" ? "desc" : "asc";
  } else {
    sortField.value = field;
    sortDir.value = "desc";
  }
}

const sorted = computed(() => {
  if (!sortField.value) return props.results;
  const field = sortField.value;
  const dir = sortDir.value === "asc" ? 1 : -1;
  return [...props.results].sort(
    (a, b) => ((a[field] ?? 0) - (b[field] ?? 0)) * dir,
  );
});

const allSelected = computed(
  () =>
    props.results.length > 0 &&
    props.results.every((r) => selected.value.has(r.place_id)),
);

function toggleAll() {
  if (allSelected.value) {
    selected.value = new Set();
  } else {
    selected.value = new Set(props.results.map((r) => r.place_id));
  }
}

function toggleRow(placeId: string) {
  const next = new Set(selected.value);
  if (next.has(placeId)) {
    next.delete(placeId);
  } else {
    next.add(placeId);
  }
  selected.value = next;
}
</script>

<template>
  <div class="overflow-x-auto">
    <table class="table table-zebra w-full">
      <thead>
        <tr>
          <th>
            <input
              type="checkbox"
              class="checkbox checkbox-sm"
              :checked="allSelected"
              @change="toggleAll"
              aria-label="Select all"
            />
          </th>
          <th>Name</th>
          <th>Category</th>
          <th class="cursor-pointer" @click="toggleSort('rating')">
            <span class="flex items-center gap-1">
              Rating
              <ArrowUpDown class="h-3 w-3" />
            </span>
          </th>
          <th class="cursor-pointer" @click="toggleSort('reviews')">
            <span class="flex items-center gap-1">
              Reviews
              <ArrowUpDown class="h-3 w-3" />
            </span>
          </th>
          <th>Address</th>
          <th class="cursor-pointer" @click="toggleSort('lead_score')">
            <span class="flex items-center gap-1">
              Pre-score
              <ArrowUpDown class="h-3 w-3" />
            </span>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="r in sorted" :key="r.place_id">
          <td @click.stop>
            <input
              type="checkbox"
              class="checkbox checkbox-sm"
              :checked="selected.has(r.place_id)"
              @change="toggleRow(r.place_id)"
            />
          </td>
          <td class="font-medium">{{ r.name }}</td>
          <td class="text-base-content/70">{{ r.category }}</td>
          <td>{{ r.rating > 0 ? r.rating.toFixed(1) : "-" }}</td>
          <td>{{ r.reviews }}</td>
          <td class="max-w-[200px] truncate text-base-content/70">
            {{ r.address }}
          </td>
          <td>{{ r.lead_score }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

// frontend/src/components/search/SearchResultsTable.tsx
import { useState } from "react";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

export interface SearchResult {
  place_id: string;
  name: string;
  category: string;
  rating: number;
  reviews: number;
  address: string;
  lead_score: number;
}

type SortKey = "rating" | "reviews" | "lead_score";
type SortDir = "asc" | "desc";

interface SearchResultsTableProps {
  results: SearchResult[];
  selected: Set<string>;
  onSelectionChange: (selected: Set<string>) => void;
}

export default function SearchResultsTable({
  results,
  selected,
  onSelectionChange,
}: SearchResultsTableProps) {
  const [sortKey, setSortKey] = useState<SortKey>("lead_score");
  const [sortDir, setSortDir] = useState<SortDir>("desc");

  const toggleSort = (key: SortKey) => {
    if (sortKey === key) {
      setSortDir(sortDir === "asc" ? "desc" : "asc");
    } else {
      setSortKey(key);
      setSortDir("desc");
    }
  };

  const sorted = [...results].sort((a, b) => {
    const mul = sortDir === "asc" ? 1 : -1;
    return (a[sortKey] - b[sortKey]) * mul;
  });

  const allSelected = results.length > 0 && selected.size === results.length;

  const toggleAll = () => {
    if (allSelected) {
      onSelectionChange(new Set());
    } else {
      onSelectionChange(new Set(results.map((r) => r.place_id)));
    }
  };

  const toggleOne = (placeId: string) => {
    const next = new Set(selected);
    if (next.has(placeId)) {
      next.delete(placeId);
    } else {
      next.add(placeId);
    }
    onSelectionChange(next);
  };

  const sortIndicator = (key: SortKey) => {
    if (sortKey !== key) return "";
    return sortDir === "asc" ? " \u2191" : " \u2193";
  };

  return (
    <div className="rounded-md border">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead className="w-10">
              <Checkbox
                checked={allSelected}
                onCheckedChange={toggleAll}
                aria-label="Select all"
              />
            </TableHead>
            <TableHead>Name</TableHead>
            <TableHead>Category</TableHead>
            <TableHead
              className="cursor-pointer select-none"
              onClick={() => toggleSort("rating")}
            >
              Rating{sortIndicator("rating")}
            </TableHead>
            <TableHead
              className="cursor-pointer select-none"
              onClick={() => toggleSort("reviews")}
            >
              Reviews{sortIndicator("reviews")}
            </TableHead>
            <TableHead>Address</TableHead>
            <TableHead
              className="cursor-pointer select-none"
              onClick={() => toggleSort("lead_score")}
            >
              Pre-score{sortIndicator("lead_score")}
            </TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {sorted.map((r) => (
            <TableRow key={r.place_id}>
              <TableCell>
                <Checkbox
                  checked={selected.has(r.place_id)}
                  onCheckedChange={() => toggleOne(r.place_id)}
                  aria-label={`Select ${r.name}`}
                />
              </TableCell>
              <TableCell className="font-medium">{r.name}</TableCell>
              <TableCell className="capitalize">
                {r.category.replace(/_/g, " ")}
              </TableCell>
              <TableCell>{r.rating.toFixed(1)}</TableCell>
              <TableCell>{r.reviews}</TableCell>
              <TableCell className="max-w-[200px] truncate">
                {r.address}
              </TableCell>
              <TableCell>{r.lead_score}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}
